### PR TITLE
Replacing reserved keywords in Firrtl circuits

### LINKED ISSUE #1: If there is a net with a name which happens to be a C++ keyword then this will cause a compiler error
Example: 

    module Adder : 
        ...
        output io : {..., signed : UInt<1>, ...}

Will cause an output of:

    UInt<1> signed;

To which the compiler complains:

    error: declaration does not declare anything [-fpermissive]

This is because `signed` is a C++ keyword, in addition to being the name of that signal.

The behavior should be changed to not emit names that are reserved words in C++.

### PR DESCRIPTION
**Pull request by MSPDUTTA**
The firrtl circuits contain reserve keywords especially here we have targeted the set of keywords in C++ and we are replacing those with "$" added after the words and makes those unique.

### CODE REVIEW

File: src/test/scala/ReplaceRsvdKeytest.scala [hunk 1]
```diff
@@ -1,20 +1,31 @@
...
+     val firrtlCompiler = new firrtl.stage.transforms.Compiler(deps)
+     val resultState = firrtlCompiler.execute(CircuitState(circuit, Seq()))
+     val tmpfile = File.createTempFile(s"${circuit.main}_transformed",".fir")
+     println(tmpfile)
+     val debugWriter = new FileWriter(tmpfile)
+     debugWriter.write(resultState.circuit.serialize)
+     debugWriter.close()
+     val sourceReader1 = Source.fromURL(getClass.getResource("/Testrsvd_correct.fir"))
+     val sourceReader2 = Source.fromFile(tmpfile)
+    // assert(sourceReader1.getLines().sameElements(sourceReader2.getLines()))
```
Comment (sbeamer) [inline src/test/scala/ReplaceRsvdKeytest.scala]: Something in the spirit of this commented out line will be needed to check it does the right thing.

File: src/test/scala/ReplaceRsvdKeytest.scala [hunk 2]
```diff
@@ -1,20 +1,31 @@
...
-  val resultState = firrtlCompiler.execute(CircuitState(circuit, Seq()))
-  val debugWriter = new FileWriter(new File(s"${circuit.main}_transformed.fir"))
-  debugWriter.write(resultState.circuit.serialize)
-  debugWriter.close()
+     val deps = firrtl.stage.Forms.LowFormOptimized ++ Seq(Dependency(ReplaceRsvdKeywords))
+     val firrtlCompiler = new firrtl.stage.transforms.Compiler(deps)
+     val resultState = firrtlCompiler.execute(CircuitState(circuit, Seq()))
+     val tmpfile = File.createTempFile(s"${circuit.main}_transformed",".fir")
+     println(tmpfile)
+     val debugWriter = new FileWriter(tmpfile)
```
Comment (sbeamer) [inline src/test/scala/ReplaceRsvdKeytest.scala]: The debugWriter may not be needed depending on how the result is checked for correctness.

File: src/main/scala/passes/ReplaceRsvdKeywords.scala [hunk 3]
```diff
@@ -0,0 +1,103 @@
...
+    case m: Mux => m.mapExpr(analyzeExpression)
+    case s: SubField => s.copy(name = maybeRename(s.name)).mapExpr(analyzeExpression)
+    case d: DoPrim => d.mapExpr(analyzeExpression)
+    case si: SubIndex => si.mapExpr(analyzeExpression)
+    case sa: SubAccess => sa.mapExpr(analyzeExpression)
+    case vi: ValidIf => vi.mapExpr(analyzeExpression)
+    case _ => e
+  }
+
+  private def analyzeIsVar(iv: IsVar):IsVar = iv match {
```
Comment (sbeamer) [inline src/main/scala/passes/ReplaceRsvdKeywords.scala]: Is support for IsVar necessary? Is this called from anywhere?

File: src/main/scala/passes/ReplaceRsvdKeywords.scala [hunk 4]
```diff
@@ -0,0 +1,103 @@
...
+    case _ => s
+  }
+
+  private def analyzeNode(f: FirrtlNode): FirrtlNode = f match {
+    case fi: Field => fi.copy(name = maybeRename(fi.name))
+    case p: Port => p.copy(name = maybeRename(p.name))
+    case _ => f
+  }
+
+  private def analyzeParam(pa: Param): Param = pa match {
```
Comment (sbeamer) [inline src/main/scala/passes/ReplaceRsvdKeywords.scala]: Is this needed? Will there be Param in low-firrtl?

File: src/main/scala/passes/ReplaceRsvdKeywords.scala [hunk 5]
```diff
@@ -0,0 +1,103 @@
...
+    case b: Block => b.mapStmt(analyzeStatement)
+    case dw: DefWire => dw.copy(name = maybeRename(dw.name))
+    case sp: Stop => sp.mapExpr(analyzeExpression)
+    case a: Attach => a.mapExpr(analyzeExpression)
+    case dr: DefRegister => dr.copy(name = maybeRename(dr.name)).mapExpr(analyzeExpression)
+    case di: DefInstance => di.copy(name = maybeRename(di.name))
+    case _ => s
+  }
+
+  private def analyzeNode(f: FirrtlNode): FirrtlNode = f match {
```
Comment (sbeamer) [inline src/main/scala/passes/ReplaceRsvdKeywords.scala]: Is this needed? Where is it called?

**Review by sbeamer — CHANGES_REQUESTED** [review]
Good start!

Also be sure to make the filenames consistent. We use lowercase names for packages/directories, and camel-case for filenames. For example, ReplaceRsvdKeytest.scala  should perhaps be ReplaceRsvdKeyTest.scala and Testrsvd.fir could be ReplacedRsvdKey.fir.

File: src/test/scala/ReplaceRsvdKeytest.scala (hunk 2 above)
Comment (MSPDUTTA) [reply src/test/scala/ReplaceRsvdKeytest.scala]: yes. I have removed that part.

File: src/test/scala/ReplaceRsvdKeytest.scala (hunk 1 above)
Comment (MSPDUTTA) [reply src/test/scala/ReplaceRsvdKeytest.scala]: when I am trying to compare two files elements y element, this check is failing due to some extra generated in "tmpfile",which is output file generated as compared to our reference output file. Still looking for some better solution

File: src/main/scala/passes/ReplaceRsvdKeywords.scala (hunk 3 above)
Comment (MSPDUTTA) [reply src/main/scala/passes/ReplaceRsvdKeywords.scala]: IsVar is related to the constraint solver (determining width) and isn't necessary here since it's used internally in a FIRRTL pass , so I have removed and run the test

File: src/main/scala/passes/ReplaceRsvdKeywords.scala (hunk 4 above)
Comment (MSPDUTTA) [reply src/main/scala/passes/ReplaceRsvdKeywords.scala]: Param has to do with ExtModules, which are (generally) Verilog module to integrate with some FIRRTL design. It is not part of low-firrtl . So , I have removed this

File: src/main/scala/passes/ReplaceRsvdKeywords.scala (hunk 5 above)
Comment (MSPDUTTA) [reply src/main/scala/passes/ReplaceRsvdKeywords.scala]: FirrtlNode is the base class for everything in the FIRRTL IR and it is not being called anywhere so removed this too

File: src/test/scala/ReplaceRsvdKeyTest.scala [hunk 6]
```diff
@@ -18,9 +18,6 @@ class ReplaceRsvdKeyTest extends FlatSpec{
      val resultState = firrtlCompiler.execute(CircuitState(circuit, Seq()))
      val tmpfile = File.createTempFile(s"${circuit.main}_transformed",".fir")
      println(tmpfile)
```
Comment (sbeamer) [inline src/test/scala/ReplaceRsvdKeyTest.scala]: Remode debug printf

File: src/test/scala/ReplaceRsvdKeyTest.scala [hunk 7]
```diff
@@ -18,9 +18,6 @@ class ReplaceRsvdKeyTest extends FlatSpec{
...
-     val debugWriter = new FileWriter(tmpfile)
-     debugWriter.write(resultState.circuit.serialize)
-     debugWriter.close()
      val sourceReader1 = Source.fromURL(getClass.getResource("/ReplacedRsvdKey_correct.fir"))
      val sourceReader2 = Source.fromFile(tmpfile)
     // assert(sourceReader1.getLines().sameElements(sourceReader2.getLines()))
```
Comment (sbeamer) [inline src/test/scala/ReplaceRsvdKeyTest.scala]: Still need way to to actually perform comparison and assert

**Review by sbeamer — CHANGES_REQUESTED** [review]
Good progress!

To finalize this pass, you will also want to ensure it is automatically called so essent can benefit from it.

**Comment by sbeamer** [comment]
The most recent commit moves things in the right direction, but it is currently failing its own CI test?

**Comment by MSPDUTTA** [comment]
yes I am still trying to understand why . after doing toString from
sourceReader it is somehow not working as expected.

**Comment by MSPDUTTA** [comment]
Fixed its own CI test. The issue is from result state when it is converting into lines of strings , there are some extra space as compared to the corrected files when converted into array of characters. if i am comparing each character of both outputs as a character array , it shows the difference. Currently comparing line by line , taking the corrected one lines as refernce and checking against resultstate's lines solves the issue and test passed.

**Review by sbeamer — APPROVED** [review]
